
---
- hosts: all
  become: true
  pre_tasks:

  - name: Ensure dpkg is configured (Ubuntu)
    raw: sudo dpkg --configure -a
    ignore_errors: yes
    changed_when: false
    when: ansible_distribution == "Ubuntu"

  - name: install update and repositories (Ubuntu)
    tags: always
    apt:
      upgrade: yes
      update_cache: yes
      cache_valid_time: 86400
    changed_when: false
    when: ansible_distribution == "Ubuntu"

- hosts: controller_ubuntu
  become: true
  roles:
    - KeystoneUbuntu
    - GlanceUbuntu
    - NovaUbuntu
